notARepository: skip
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
  - key: "O"
    command: "tmux new-window opencode"
    description: "open opencode in new tmux tab"
    context: "status, files"
  - key: "O"
    command: "tmux new-window 'cd {{.SelectedWorktree.Path}} && opencode'"
    description: "open opencode in new tmux tab for worktree"
    context: "worktrees"
  - key: "E"
    command: "tmux new-window nvim"
    description: "open nvim in new tmux tab"
    context: "status, files"
  - key: "E"
    command: "tmux new-window 'cd {{.SelectedWorktree.Path}} && nvim'"
    description: "open nvim in new tmux tab for worktree"
    context: "worktrees"
  - key: "T"
    command: "tmux new-window zsh"
    description: "open terminal in new tmux tab"
    context: "status, files"
  - key: "T"
    command: "tmux new-window 'cd {{.SelectedWorktree.Path}} && zsh'"
    description: "open terminal in new tmux tab for worktree"
    context: "worktrees"

git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --syntax-theme base16-256 -s
os:
  edit: "nvim {{filename}}"
gui:
  # Use the mocha catppuccin theme
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
