[general]
import =[
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "Buttonless"
opacity = 0.85
blur = true
padding = { x = 10, y = 10 }

[font]
normal.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"

size = 15.0

[env]
TERM = "xterm-256color"
